
export const OFFLINE_NAMES_BY_COUNTRY: Record<string, string[]> = {
  "Australia": [
    "Charlotte Smith", "Olivia Jones", "Amelia Williams", "Isla Brown", "Mia Wilson", "Ava Taylor", "Grace Morten", "Willow Clarke", "Harper Johnston", "Chloe White",
    "Ruby Thompson", "Ivy Anderson", "Evie Walker", "Isabella Wright", "Sophie Hall", "Matilda Young", "Georgia King", "Ella Baker", "Zoe Campbell", "Scarlett Hill",
    "Emma Scott", "Layla Green", "Lily Adams", "Aria Mitchell", "Maya Nelson", "Lucy Carter", "Hazel Roberts", "Florence Phillips", "Mila Evans", "Daisy Turner",
    "Audrey Morgan", "Alice Parker", "Freya Collins", "Lola Edwards", "Imogen Stewart", "Violet Morris", "Elsie Nguyen", "Sienna Murphy", "Penelope Cook", "Poppy Rogers",
    "Luna Morgan", "Piper Kelly", "Willow Bell", "Eleanor Ward", "Harriet Cox", "Elizabeth Richardson", "Mabel Marshall", "Billie Bailey", "Stella Wood", "Addison Knight",
    "Rose Bennett", "Nora Miller", "Aurora Gray", "Pippa Cooper", "Bonnie Hughes", "Sadie Harrison", "Thea Graham", "Adelaide Sullivan", "Olive Foster", "Clara Ross",
    "Indigo Perry", "Tilly Russell", "Indiana Grant", "Evelyn Payne", "Maeve Fisher", "Lulu Butler", "Margot Simmons", "Zara Foster", "Hallie Jenkins", "Remi Stephens",
    "Summer Porter", "Savannah Wallace", "Zelda Hunter", "Ayla Hicks", "Eden Gardner", "Heidi Crawford", "Cleo Boyd", "Daphne Mason", "Eliza Dixon", "Eve Hunt",
    "Francesca Palmer", "Georgia Robertson", "Gia Black", "Gemma Holmes", "Harlow Stone", "Hope Meyer", "Iris Bishop", "Jade Fox", "Jasmine Day", "Juno Howell",
    "Kaia Mills", "Kira Knight", "Lacey Arnold", "Lara Berry", "Leila Brooks", "Lexi Duncan", "Lila Fowler", "Lottie George", "Lyric Gibson", "Macy Harper",
    "Madeline Hart", "Mae Hudson", "Maggie Jacobs", "Marlowe James", "Marnie Jordan", "Mina Kennedy", "Nellie Lawrence", "Nina Little", "Nova Logan", "Nya Long",
    "Ophelia Lowe", "Paige Lucas", "Paloma Marsh", "Pearl McCoy", "Phoebe McDonald", "Phoenix McKenzie", "Polly McLeod", "Quinn Meade", "Rae Mendoza", "Raina Mercer",
    "Reese Miller", "Ria Mills", "Romy Moore", "Rory Morgan", "Sasha Morris", "Saylor Morrison", "Selena Murray", "Skye Myers", "Sloane Nash", "Talia Newton",
    "Tallulah Nolan", "Tatum Norris", "Tegan O'Brien", "Tessa O'Connell", "Theodora O'Connor", "Tia O'Donnell", "Tora O'Hara", "Tove O'Neill", "Trixie Owens", "True Page",
    "Uma Palmer", "Una Parker", "Vada Patterson", "Veda Payne", "Vera Pearson", "Vida Perry", "Vyla Peters", "Willa Phillips", "Winnie Pierce", "Wren Porter",
    "Xanthe Potter", "Xaya Powell", "Xyla Price", "Yara Quinn", "Yuna Ramsey", "Yvaine Reed", "Zahara Reid", "Zani Rhodes", "Zaya Rice", "Zia Richards",
    "Zora Richardson", "Zoya Roberts", "Zuri Robertson", "Zyla Robinson", "Ainsley Rogers", "Alani Ross", "Alara Russell", "Alia Ryan", "Alora Sanders", "Amara Scott",
    "Anaya Shaw", "Anika Simpson", "Anora Smith", "Arlo Stephens", "Asher Stevens", "Aura Stewart", "Aurelia Stone", "Aviana Sullivan", "Azalea Taylor", "Baya Thomas",
    "Belen Thompson", "Bellamy Turner", "Bexley Walker", "Birdie Wallace", "Blaire Ward", "Bria Watson", "Briar White", "Calla Williams", "Capri Wilson", "Carys Wood",
    "Cassia Wright", "Caya Young", "Celine Abbott", "Chaya Barnes", "Cora Bell", "Cosima Bennett", "Della Brooks", "Demi Butler", "Devyn Campbell", "Dierdre Carter",
    "Elora Clark", "Elowen Cole", "Emani Collins", "Ember Cook", "Emery Cooper", "Etta Davis", "Ezra Dixon", "Fia Edwards", "Fraya Evans", "Greer Fisher", "Gwen Foster"
  ],
  "Sweden": [
    "Alice Nilsson", "Maja Andersson", "Elsa Johansson", "Astrid Eriksson", "Wilma Larsson", "Alma Olsson", "Saga Persson", "Freja Karlsson", "Ebba Svensson", "Ella Gustafsson",
    "Lilly Pettersson", "Sigrid Jonsson", "Selma Jansson", "Nellie Hansson", "Ines Bengtsson", "Vera Jönsson", "Molly Lindberg", "Ester Jakobsson", "Lea Magnusson", "Clara Lindström",
    "Agnes Olofsson", "Julia Lindgren", "Isabelle Axelsson", "Linnea Berg", "Signe Bergström", "Tilda Lundberg", "Elin Lindqvist", "Alva Nyström", "Tuva Arvidsson", "Liv Holmberg",
    "Ida Hellström", "Klara Nyberg", "Siri Björk", "Ellen Isaksson", "Meja Åberg", "Nova Wallin", "Emelie Mårtensson", "Lova Gunnarsson", "Moa Forsberg", "Ronja Nordström",
    "Tyra Sjögren", "Minna Björklund", "Hanna Sundberg", "Juni Danielsson", "Lykke Engström", "Lovisa Eklund", "Ingrid Fransson", "Sofia Lundgren", "Majken Bergman", "Olivia Söderberg",
    "Hedda Holm", "Tove Stenström", "Matilda Lundqvist", "Greta Viklund", "Svea Bergkvist", "Edit Lindblom", "Beata Hedlund", "Thea Samuelsson", "Felicia Eliasson", "Linn Malm",
    "Amelia Dahlberg", "Tindra Hammarström", "Elvira Sjöberg", "Malin Berglund", "Kajsa Sandström", "Sofia Ström", "Lisa Öberg", "Emmy Hermansson", "Stina Blomqvist", "Jasmine Nordin",
    "Nicole Westerberg", "Cornelia Ahlin", "Leah Boström", "Adele Söderqvist", "Annie Löfgren", "Bodil Wahlström", "Disa Almqvist", "Eira Sundqvist", "Frida Malmberg", "Gudrun Hellman",
    "Hilma Norberg", "Irma Ekström", "Jonna Lind", "Karin Björkdahl", "Lotta Söderlund", "Märta Dahlström", "Nora Blom", "Ottilia Strand", "Petra Falk", "Rakel Bergquist",
    "Siv Sjöström", "Tora Wahlgren", "Ulla Lundvall", "Vanja Nyqvist", "Wendela Holmquist", "Ylva Björling", "Åsa Lindroth", "Birgitta Hedqvist", "Gunilla Bergfors", "Kerstin Sjöholm",
    "Barbro Granlund", "Viveka Söderblom", "Gunnel Hellström", "Annika Lindskog", "Susanne Wahlberg", "Monica Sjölander", "Yvonne Lindh", "Lena Björkman", "Inger Söderhäll", "Christina Blomberg",
    "Margareta Wahlman", "Erika Hellsten", "Ulrika Norén", "Sanna Dahl", "Jenny Söder", "Linda Blomstrand", "Marie Hellqvist", "Sara Nyman", "Anna Björnsdotter", "Karin Lund",
    "Josefin Sjöstrand", "Amanda Lindholm", "Emelie Wahl", "Emma Hell", "Johanna Norström", "Sofie Dahlin", "Malin Södersten", "Linnéa Blomdahl", "Viktoria Hellström", "Louise Nyvall",
    "Ida Björksten", "Hanna Lindsten", "Rebecka Wahlén", "Elin Hellgren", "Moa Norgren", "Tilda Dahlén", "Alva Söderström", "Lova Blomqvist", "Klara Hellberg", "Signe Nystedt",
    "Astrid Lind", "Elsa Sjö", "Ebba Blom", "Agnes Hell", "Saga Nord", "Freja Söder", "Alma Berg", "Wilma Lind", "Alice Holm", "Maja Sten",
    "Selma Dal", "Ellen Björk", "Ines Sjö", "Vera Berg", "Sigrid Lind", "Ester Holm", "Julia Sten", "Signe Blom", "Lilly Nord", "Nellie Söder",
    "Molly Dal", "Tuva Björk", "Tyra Sjö", "Lykke Berg", "Majken Lind", "Hedda Holm", "Juni Sten", "Meja Blom", "Minna Nord", "Siri Söder",
    "Ronja Dal", "Tove Björk", "Lova Sjö", "Hanna Berg", "Elin Lind", "Linnéa Holm", "Moa Sten", "Kajsa Blom", "Stina Nord", "Sofia Söder",
    "Agda Lind", "Alfhild Berg", "Alva Holm", "Anja Sten", "Ann-Mari Blom", "Barbro Nord", "Beata Söder", "Berta Dal", "Birgit Björk", "Brita Sjö",
    "Dagmar Berg", "Dagny Lind", "Dorotea Holm", "Eivor Sten", "Elna Blom", "Elsa-Britt Nord", "Embla Söder", "Estrid Dal", "Gerda Björk", "Gullan Sjö",
    "Gun Berg", "Gunborg Lind", "Gunhild Holm", "Gunvor Sten", "Helfrid Blom", "Hildur Nord", "Hillevi Söder", "Hjördis Dal", "Hulda Björk", "Ingeborg Sjö"
  ],
  "Mexico": [
    "Ximena García", "Sofía Martínez", "Valentina Hernández", "Camila López", "María González", "Mariana Pérez", "Isabella Rodríguez", "Daniela Sánchez", "Renata Ramírez", "Victoria Cruz",
    "Lucía Flores", "Natalia Gómez", "Fernanda Morales", "Julieta Vásquez", "Gabriela Jiménez", "Andrea Reyes", "Elena Díaz", "Alejandra Torres", "Paulina Gutiérrez", "Montserrat Ruiz",
    "Jimena Mendoza", "Regina Aguilar", "Ana Méndez", "Guadalupe Moreno", "Karla Castillo", "Paola Romero", "Valeria Álvarez", "Vanessa García", "Saraí Martínez", "Claudia Hernández",
    "Liliana López", "Mónica González", "Beatriz Pérez", "Rosa Rodríguez", "Leticia Sánchez", "Juana Ramírez", "Adriana Cruz", "Verónica Flores", "Blanca Gómez", "Silvia Morales",
    "Martha Vásquez", "Irma Jiménez", "Yolanda Reyes", "Gloria Díaz", "Teresa Torres", "Alicia Gutiérrez", "Sonia Ruiz", "Lourdes Mendoza", "Cecilia Aguilar", "Margarita Méndez",
    "Josefina Moreno", "Angélica Castillo", "Francisca Romero", "Alma Álvarez", "Diana García", "Erika Martínez", "Karina Hernández", "Lorena López", "Patricia González", "Sandra Pérez",
    "Nancy Rodríguez", "Marisol Sánchez", "Mayra Ramírez", "Jessica Cruz", "Lizbeth Flores", "Brenda Gómez", "Alejandra Morales", "Guadalupe Vásquez", "María Jiménez", "Fátima Reyes",
    "Yatziry Díaz", "Itzel Torres", "Citlali Gutiérrez", "Nayeli Ruiz", "Zulema Mendoza", "Xochitl Aguilar", "Anahí Méndez", "Araceli Moreno", "Isela Castillo", "Nallely Romero",
    "Yadira Álvarez", "Maritza García", "Mireya Martínez", "Selene Hernández", "Ivonne López", "Perla González", "Ofelia Pérez", "Socorro Rodríguez", "Concepción Sánchez", "Guillermina Ramírez",
    "Ernestina Cruz", "Esthela Flores", "Eugenia Gómez", "Evangelina Morales", "Felicitas Vásquez", "Fidela Jiménez", "Florencia Reyes", "Fortunata Díaz", "Genoveva Torres", "Gertrudis Gutiérrez",
    "Graciela Ruiz", "Gregoria Mendoza", "Hermelinda Aguilar", "Hilaria Méndez", "Hipólita Moreno", "Ignacia Castillo", "Inés Romero", "Inocencia Álvarez", "Isabel García", "Isidora Martínez",
    "Jacinta Hernández", "Jerónima López", "Joaquina González", "Josefa Pérez", "Julia Rodríguez", "Juliana Sánchez", "Justina Ramírez", "Leonor Cruz", "Liberata Flores", "Lidia Gómez",
    "Lorenza Morales", "Luciana Vásquez", "Luisa Jiménez", "Luz Reyes", "Maclovia Díaz", "Magdalena Torres", "Manuela Gutiérrez", "Marcelina Ruiz", "Margarita Mendoza", "María Aguilar",
    "Mariana Méndez", "Marina Moreno", "Marta Castillo", "Martina Romero", "Matilde Álvarez", "Maximiana García", "Micaela Martínez", "Modesta Hernández", "Nicolasa López", "Otilia González",
    "Pabla Pérez", "Pacífica Rodríguez", "Palmira Sánchez", "Pascuala Ramírez", "Pastora Cruz", "Paula Flores", "Paulina Gómez", "Perfecta Morales", "Petrona Vásquez", "Pía Jiménez",
    "Plácida Reyes", "Policarpa Díaz", "Pomposa Torres", "Práxedes Gutiérrez", "Presentación Ruiz", "Primitiva Mendoza", "Priscila Aguilar", "Prócula Méndez", "Prudencia Moreno", "Pura Castillo",
    "Queta Romero", "Quiteria Álvarez", "Rafaela García", "Ramona Martínez", "Raquel Hernández", "Raymunda López", "Rebeca González", "Refugio Pérez", "Regina Rodríguez", "Remedios Sánchez",
    "Reyna Ramírez", "Ricarda Cruz", "Rita Flores", "Rocío Gómez", "Romana Morales", "Rosaura Vásquez", "Rosenda Jiménez", "Rufina Reyes", "Ruperta Díaz", "Sabina Torres",
    "Salomé Gutiérrez", "Salustia Ruiz", "Salvadora Mendoza", "Samanta Aguilar", "Sanjuana Méndez", "Santa Moreno", "Santana Castillo", "Sara Romero", "Saturnina Álvarez", "Sebastiana García",
    "Secundina Martínez", "Senorina Hernández", "Serafina López", "Severa González", "Severiana Pérez", "Simona Rodríguez", "Sixta Sánchez", "Socorro Ramírez", "Sofía Cruz", "Sol Flores",
    "Soledad Gómez", "Sonia Morales", "Susana Vásquez", "Teodora Jiménez", "Teófila Reyes", "Teresa Díaz", "Tomasa Torres", "Trinidad Gutiérrez", "Ursula Ruiz", "Valeriana Mendoza"
  ],
  "Japan": [
    "Sakura Sato", "Hinata Suzuki", "Aoi Takahashi", "Ichika Tanaka", "Akari Watanabe", "Sara Ito", "Yui Yamamoto", "Nico Nakamura", "Riko Kobayashi", "Mio Kato",
    "Mei Yoshida", "Hina Yamada", "Kaho Sasaki", "Suzu Yamaguchi", "Uta Saito", "Kokoa Matsumoto", "Koharu Inoue", "Miyu Kimura", "Tsumugi Hayashi", "Saki Shimizu",
    "Reina Yamazaki", "Rio Abe", "Hiyori Ikeda", "Yuna Hashimoto", "Mina Yamashita", "Sora Ishikawa", "Hana Mori", "Mizuki Maeda", "Nana Fujita", "Kanade Okada",
    "Asahi Goto", "Karin Hasegawa", "Ema Murakami", "Yume Kondo", "Maki Ishii", "Rin Sakamoto", "Aya Endo", "Yuka Aoki", "Nao Fujii", "Sana Nishimura",
    "Mari Fukuda", "Kiyomi Ota", "Haruka Miura", "Emi Fujiwara", "Shiori Okamoto", "Mana Matsuda", "Rika Nakagawa", "Natsumi Nakano", "Kumi Matsui", "Misaki Noguchi",
    "Aiko Koyama", "Tomoko Tamura", "Kaori Kaneko", "Keiko Wada", "Kyoko Ono", "Naomi Takeuchi", "Yoko Chiba", "Akiko Hara", "Mayumi Takeda", "Miki Imai",
    "Rumi Shibata", "Sae Ueda", "Chihiro Enomoto", "Ayaka Sugiyama", "Katsumi Kojima", "Maho Ando", "Risa Kudo", "Haru Takagi", "Yuki Morita", "Natsuko Yokoyama",
    "Sayaka Miyazaki", "Asuka Ueno", "Mami Baba", "Miyuki Sano", "Chieko Matsuoka", "Kazumi Komatsu", "Yukiko Shimada", "Etsuko Konishi", "Satoko Hirano", "Michiko Matsumura",
    "Sachiko Kikuchi", "Reiko Kubo", "Masako Nojima", "Tomoe Miyamoto", "Nobuko Hoshino", "Ryoko Sugimoto", "Kozue Matsuyama", "Toshiko Nakayama", "Fumiko Uchida", "Chizuru Sato",
    "Sae Suzuki", "Ayame Takahashi", "Hotaru Tanaka", "Kanna Watanabe", "Momoka Ito", "Nanami Yamamoto", "Sumire Nakamura", "Tsukushi Kobayashi", "Yuzu Kato", "Anzu Yoshida",
    "Ayane Yamada", "Chiaki Sasaki", "Fubuki Yamaguchi", "Hazuki Saito", "Iroha Matsumoto", "Izumi Inoue", "Koyuki Kimura", "Misora Hayashi", "Mitsuki Shimizu", "Nagisa Yamazaki",
    "Natsume Abe", "Ranka Ikeda", "Riona Hashimoto", "Shizuku Yamashita", "Suzume Ishikawa", "Tamaki Mori", "Umi Maeda", "Wakaba Fujita", "Yayoi Okada", "Yoshino Goto",
    "Aika Hasegawa", "Aimi Murakami", "Aina Kondo", "Akane Ishii", "Akira Sakamoto", "Amane Endo", "Anri Aoki", "Arisa Fujii", "Ayano Nishimura", "Azusa Fukuda",
    "Erena Ota", "Fuka Miura", "Haru Fujiwara", "Himari Okamoto", "Honoka Matsuda", "Ibuki Nakagawa", "Junna Nakano", "Kanon Matsui", "Karen Noguchi", "Kasumi Koyama",
    "Kirari Tamura", "Kokomi Kaneko", "Kurumi Wada", "Madoka Ono", "Mai Takeuchi", "Manaka Chiba", "Marika Hara", "Minami Takeda", "Mirai Imai", "Momoko Shibata",
    "Mone Ueda", "Nagisa Enomoto", "Nanako Sugiyama", "Nene Kojima", "Noa Ando", "Nonoka Kudo", "Raina Takagi", "Ran Morita", "Rei Yokoyama", "Remi Miyazaki",
    "Ria Ueno", "Rika Baba", "Rina Sano", "Rino Matsuoka", "Rion Komatsu", "Rira Shimada", "Risa Konishi", "Runa Hirano", "Ryoka Matsumura", "Saki Kikuchi",
    "Sakura Kubo", "Sana Nojima", "Seira Miyamoto", "Sena Hoshino", "Shion Sugimoto", "Suzy Matsuyama", "Yae Nakayama", "Yoko Uchida", "Yua Sato", "Yui Suzuki",
    "Yuka Takahashi", "Yuki Tanaka", "Yuko Watanabe", "Yumi Ito", "Yuna Yamamoto", "Yura Nakamura", "Yuri Kobayashi", "Yurina Kato", "Yuzu Yoshida", "Yuzuha Yamada",
    "Ai Sasaki", "Ami Yamaguchi", "Amu Saito", "An Matsumoto", "Asa Inoue", "Chi Kimura", "Eri Hayashi", "Fuyu Shimizu", "Iyo Yamazaki", "Kae Abe",
    "Kai Ikeda", "Kao Hashimoto", "Kiho Yamashita", "Kiku Ishikawa", "Kimi Mori", "Kiyo Maeda", "Kumi Fujita", "Maki Okada", "Mei Goto", "Mio Hasegawa"
  ],
  "Brazil": [
    "Helena Silva", "Alice Oliveira", "Laura Souza", "Maria Santos", "Sophia Ferreira", "Manuela Alves", "Maitê Pereira", "Liz Lima", "Cecília Gomes", "Isabella Ribeiro",
    "Luísa Martins", "Eloá Carvalho", "Valentina Rocha", "Antonella Almeida", "Lara Lopes", "Júlia Soares", "Gaia Fernandes", "Lorena Vieira", "Lívia Barbosa", "Giovanna Machado",
    "Beatriz Cardoso", "Melissa Teixeira", "Isadora Rocha", "Mariana Araújo", "Nicole Nascimento", "Rafaela Cavalcante", "Yasmin Dias", "Madalena Castro", "Lavínia Barbosa", "Letícia Nunes",
    "Camila Oliveira", "Bruna Silva", "Carolina Santos", "Fernanda Souza", "Gabriela Ferreira", "Jéssica Pereira", "Larissa Alves", "Natália Lima", "Priscila Gomes", "Renata Ribeiro",
    "Tatiane Martins", "Vanessa Carvalho", "Aline Rocha", "Andressa Almeida", "Barbara Lopes", "Cristiane Soares", "Daniela Fernandes", "Eliane Vieira", "Fabiana Barbosa", "Flávia Machado",
    "Gisele Cardoso", "Ivone Teixeira", "Janaina Rocha", "Kelly Araújo", "Luciana Nascimento", "Márcia Cavalcante", "Patrícia Dias", "Regina Castro", "Sônia Barbosa", "Zuleica Nunes",
    "Adriana Silva", "Alexandra Oliveira", "Andreia Santos", "Ângela Souza", "Arlete Ferreira", "Benedita Pereira", "Carla Alves", "Cássia Lima", "Cleide Gomes", "Dalva Ribeiro",
    "Edna Martins", "Elza Carvalho", "Eunice Rocha", "Fátima Almeida", "Geralda Lopes", "Heloísa Soares", "Iara Fernandes", "Inês Vieira", "Iracema Barbosa", "Irene Machado",
    "Izabel Cardoso", "Jandira Teixeira", "Joana Rocha", "Judite Araújo", "Leda Nascimento", "Lourdes Cavalcante", "Lúcia Dias", "Luzia Castro", "Magali Barbosa", "Margarida Nunes",
    "Marilda Silva", "Marília Oliveira", "Marina Santos", "Marly Souza", "Mírian Ferreira", "Nair Pereira", "Neide Alves", "Neuza Lima", "Nilza Gomes", "Noêmia Ribeiro",
    "Odete Martins", "Olga Carvalho", "Palmira Rocha", "Quitéria Almeida", "Raquel Lopes", "Rebeca Soares", "Rita Fernandes", "Rosana Vieira", "Rosângela Barbosa", "Rosemary Machado",
    "Rute Cardoso", "Sandra Teixeira", "Sebastiana Rocha", "Selma Araújo", "Silvana Nascimento", "Sílvia Cavalcante", "Simone Dias", "Suzana Castro", "Telma Barbosa", "Tereza Nunes",
    "Terezinha Silva", "Valdete Oliveira", "Valdirene Santos", "Vanda Souza", "Vera Ferreira", "Vilma Pereira", "Zélia Alves", "Zilda Lima", "Zoraide Gomes", "Adelaide Ribeiro",
    "Agripina Martins", "Almerinda Carvalho", "Amélia Rocha", "Anália Almeida", "Anunciada Lopes", "Aparecida Soares", "Aristotelina Fernandes", "Ascensão Vieira", "Assunta Barbosa", "Aurélia Machado",
    "Aurora Cardoso", "Balbina Teixeira", "Belmira Rocha", "Bernadete Araújo", "Cândida Nascimento", "Carmem Cavalcante", "Catarina Dias", "Celeste Castro", "Célia Barbosa", "Cely Nunes",
    "Chiquinha Silva", "Clarice Oliveira", "Claudete Santos", "Clemência Souza", "Clotilde Ferreira", "Conceição Pereira", "Consuelo Alves", "Cordélia Lima", "Corina Gomes", "Custódia Ribeiro",
    "Dandara Martins", "Darci Carvalho", "Deolinda Rocha", "Dina Almeida", "Dionísia Lopes", "Dirce Soares", "Diva Fernandes", "Divina Vieira", "Dolores Barbosa", "Domitila Machado",
    "Dona Cardoso", "Donária Teixeira", "Dora Rocha", "Doralice Araújo", "Dulce Nascimento", "Edite Cavalcante", "Eglantina Dias", "Elda Castro", "Eleonora Barbosa", "Elisa Nunes",
    "Elisabete Silva", "Elmira Oliveira", "Elsa Santos", "Elvira Souza", "Ema Ferreira", "Emanuela Pereira", "Emília Alves", "Enedina Lima", "Eny Gomes", "Ercília Ribeiro",
    "Erotildes Martins", "Eshiley Carvalho", "Esmeralda Rocha", "Esperança Almeida", "Estela Lopes", "Ester Soares", "Etelvina Fernandes", "Eudóxia Vieira", "Eugênia Barbosa", "Eulália Machado",
    "Eunice Cardoso", "Eustáquia Teixeira", "Eva Rocha", "Evangelina Araújo", "Eveline Nascimento", "Expedita Cavalcante", "Felismina Dias", "Filomena Castro", "Firmina Barbosa", "Florença Nunes"
  ]
};

export const ALL_OFFLINE_NAMES = Object.values(OFFLINE_NAMES_BY_COUNTRY).flat();
